#ifndef REB_CAN_TX_H
#define REB_CAN_TX_H

#include <stdbool.h>

#include "can_codec.h"
#include "can_frame.h"
#include "can_ids.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Status codes returned by CAN TX functions.
 */
typedef enum
{
    CAN_TX_STATUS_OK = 0,
    CAN_TX_STATUS_NULL_POINTER,
    CAN_TX_STATUS_UNSUPPORTED_MESSAGE,
    CAN_TX_STATUS_DIRECTION_MISMATCH,
    CAN_TX_STATUS_ENCODE_ERROR
} can_tx_status_t;

/**
 * @brief Container for all TX messages generated by REB.
 *
 * The selected payload is defined by msg_id.
 */
typedef struct
{
    can_msg_id_t msg_id;
    union
    {
        can_reb_status_t reb_status;
        can_reb_derate_cmd_t reb_derate_cmd;
        can_reb_prevent_start_t reb_prevent_start;
        can_reb_gps_request_t reb_gps_request;
    } data;
} can_tx_message_t;

/**
 * @brief Check whether a message is supported as TX by REB.
 *
 * @param msg_id Logical message identifier
 * @return true if the message direction is TX
 */
bool can_tx_is_message_supported(can_msg_id_t msg_id);

/**
 * @brief Encode a logical TX message into a CAN frame.
 *
 * @param msg Pointer to logical TX message
 * @param out_frame Pointer to encoded CAN frame
 * @return CAN TX status code
 */
can_tx_status_t can_tx_build_frame(
    const can_tx_message_t *msg,
    can_frame_t *out_frame);

#ifdef __cplusplus
}
#endif

#endif /* REB_CAN_TX_H */